trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

jobs:
  - job: BuildAndTest
    displayName: "Build and test"
    pool:
      name: Default
    variables:
      BASH_ENV: /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      NIX_CONFIG: extra-experimental-features = nix-command flakes
    steps:
      - checkout: self
      - script: |
          NIX_PATH=nixpkgs=channel:nixos-24.05 nix build --option sandbox false --option allow-network true
        displayName:
          "Nix build and test"
