trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

jobs:
  - job: BuildAndTest
    displayName: "Build and test"
    pool:
      name: Default
    variables:
      BASH_ENV: /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      NIX_CONFIG: extra-experimental-features = nix-command flakes
    steps:
      - checkout: self
      - script: |
          #!/bin/bash

          my_test="${MY_TEST_VAR:-${MY_TEST_VAR:-my-test}}"
          echo "${my_test}"
        displayName:
          "Nix build and test"
