trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  BASH_ENV: /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  NIX_CONFIG: extra-experimental-features = nix-command flakes

steps:
  - checkout: self

  - script: |
      nix build
    displayName: 'Build and test' 
