trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.407'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet restore
    displayName: 'Restore project'

  - script: |
      dotnet build --configuration Release
    displayName: 'Build project'

  - script: |
      dotnet test Aoc2023.Tests/ --verbosity normal --configuration Release
    displayName: 'Run unit tests'
